version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: .
    volumes:
      - ./app:/app:cached
    ports:
      - "3000:3000"
    tty: true
    # environment:
    #   - HOST=0.0.0.0
    #   - port=80
    #   - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install  && yarn dev"
