version: '3.9'

services:
  nuxt:
    container_name: nuxt3-firebaseauth
    image: nuxt3-firebaseauth:latest
    build: .
    volumes:
      - ./app:/app:cached
    ports:
      - "3000:3000"
    tty: true
    # command: sh -c "npm install  && npm run dev"
